language: cpp
compiler: clang
sudo: false

addons:
  apt:
    packages:
      - g++-multilib

install:
  - wget https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6488-linux.tar.gz -O /tmp/sourcemod.tar.gz
  - tar -xzvf /tmp/sourcemod.tar.gz

before_script:
  - chmod +rx addons/sourcemod/scripting/spcomp
  - chmod +rx addons/sourcemod/scripting/compile.sh
  - cd addons/sourcemod/scripting/
  
script:
  - ./spcomp mapchoices.sp
  - ./spcomp mapchoices-mapend.sp
  - ./spcomp mapchoices-filters/mapchoices-recent.sp
  - ./spcomp mapchoices-games/mapchoices-csgo.sp
  - ./spcomp mapchoices-games/mapchoices-tf2.sp
  - ./spcomp mapchoices-votesystems/mapchoices-nativevotes.sp
